### ISSUE TITLE
Offical Site of Raspberry Pints

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#31] opened 2014-01-12 19:05 UTC
http://raspberrypints.com/

I was able to pick up the domain for this today, as this is your project thad I can give  the domain to you at any point if you would like. I also made you guys email addresses thad@raspberrypints.com and jay@raspberrypints.com your passwords are Pa$$w0rd I sugegst you login and change them.

**Comment by thadius856** [comment] 2014-01-12 19:43
Holy. Mother. of. God.

**Comment by Skemp45** [comment] 2014-01-12 19:50
also, What do you think of this?
![raspberrypints](https://f.cloud.github.com/assets/6318869/1896939/b48355ea-7bc2-11e3-9029-8eca2d698bbf.png)

**Comment by Skemp45** [comment] 2014-01-12 19:50
a raspberry as the dot on the I instead of a dot

**Comment by thadius856** [comment] 2014-01-12 19:58
I thought of that yesterday when I was building the graphic. Unfortunately: http://www.raspberrypi.org/trademark-rules So I didn't use it.

What about a pint glass that looks like a raspberry, maybe with the leaves instead of a head of foam?

**Comment by thadius856** [comment] 2014-01-12 19:59
Added the POP server to my primary Gmail account.

Unfortunately, I need to access the account before I can confirm it.

Do you have a web interface loaded? I can download a POP/SMTP client if needed. But, how do I change the pw without a web interface?

**Comment by Skemp45** [comment] 2014-01-12 20:11
Go to email.raspberrypints.com and login

**Comment by thadius856** [comment] 2014-01-12 20:13
Silly me. I kept trying mail.raspberrypints.com. :+1:

Password set. Gmail forwarding setup, and I can now "send as" from Gmail (they send, but spoof the sender to show the other domain).

**Comment by thadius856** [comment] 2014-01-12 20:14
Were you thinking about making a full site? Have you pre-paid hosting?

Here's a free alternative we could point the domain at if we didn't feel like making a whole site.

http://pages.github.com/

**Comment by Skemp45** [comment] 2014-01-12 20:14
Nice!!!!!

**Comment by Skemp45** [comment] 2014-01-12 20:15
I would be cool with pages. And just forwarding it

**Comment by Skemp45** [comment] 2014-01-12 20:16
I might have an issue with the admin panel......  I am reading the tos now from where I bought it years ago I will let you know

**Comment by thadius856** [comment] 2014-01-12 22:34
Just now saw this entry. My mistake.

**Comment by thadius856** [comment] 2014-01-12 23:57
Any updates? I'd be happy to look over a document with you, if you like.

Really antsy to start digging in with the config options.

**Comment by Boombrewer** [comment] 2014-01-13 00:52
What's the username and password?

I'd like to poke around and see how it runs.

**Comment by thadius856** [comment] 2014-01-13 00:54
L: github
P: Pa$$w0rd

The admin interface hasn't been commited yet, so you won't find it on the latest commit.

**Comment by JayUnt** [comment] 2014-01-13 01:11
Nice!  I haven't checked my email all day. Good work.

**Comment by Boombrewer** [comment] 2014-01-13 01:12
Nice.

I can be the 'average joe' to test and see just how easy it is to operate.  Everything looks good so far.

Why the redundancy between Beer List and Tap List both showing and allowing an edit of the tap number?

**Comment by Skemp45** [comment] 2014-01-13 01:16
http://themeforest.net/licenses/regular

after reading through this I know no more than before I started reading it.... this makes no sense to me but maybe you can understand. Will it be ok to use in the application as the admin panel?

Sorry if its not. I still at least have alot of the framework worked out if we cant use the theme. Alot of the icons etc are mine through it is really just the layout and navigation that's the theme. Let me know

**Comment by thadius856** [comment] 2014-01-13 02:03
> Why the redundancy between Beer List and Tap List both showing and allowing an edit of the tap number?

That's temporary while we transition. The Beer List will become a recipe list, so to speak. The Tap List will let you select a beer from the beer list, assign it a Tap Number, specify an OG/FG/SRM/IBU for this specific batch, and (some day) allow you to specify the size of the keg and how full it was when you put it in the keezer.

It'll be removed from the Beer List sooner than later.

**Comment by thadius856** [comment] 2014-01-13 02:13
> after reading through this I know no more than before I started reading it.... 

No probs, man. I read Department of Defense and Air Force policy all day for a living. Lets go paragraph by paragraph.
1. You can use this software. So can other users that buy it. Buying it doesn't mean that we won't sell it to somebody else also.
2. You can install it once per time you pay for it.
3. In other words, you can use it on ONE public site per purchase.
4. You can sell your license to a customer (like if you were hired as their web designer, you can pass on the cost).
5. If you make something that works offline, you can make as many identical copies as you like, but the copies must be free (you can still charge for the first one).
6. You can edit or manipulate what you bought, but that doesn't mean you own the original.
7. You can't resell copies of their software that you don't own.
8. Again, you can't re-sell copies.
9. Please don't extract single files from our source for the purpose of stealing the code.
10. Don't enable or teach somebody else to do #9.
11. Doesn't seem to apply in this case.
12. If the author specifies an additional license, you must also follow it. (did they, that you know of?)
13. You must carry forward any GPL licenses inherited (did they specify one, that you know of?)
14. Don't do illegal things with our product, like selling drugs or manage pimp stock.
15. Legal bs. Don't do stupid things.
16. Legal bs. Don't break the terms.
17. Legal bs. Buying a copy doesn't mean you own the original.

As long as this is the only public copy you have, #4 means you can use it here. #5 means you can distribute it like we are, as long as you don't charge for it.

**Comment by thadius856** [comment] 2014-01-13 02:23
I think you're in the clear, as long as this is the only public install/distro you have, and you aren't _aware_ of any GPL license restrictions.

**Comment by Skemp45** [comment] 2014-01-13 02:40
They did not state any other GPL LICENSE  restrictions. so I think we are golden!!!!!! Wooohoooo

**Comment by thadius856** [comment] 2014-01-13 02:40
Great. LET US PROCEED!

Care to post the admin page so we can noodle? ;)

**Comment by JayUnt** [comment] 2014-01-13 02:55
yeah, looking it over, it seems like we are good to use it.

"You can make any number of copies of the single End Product, as long as the End Product is distributed for Free." This seems exactly like we are doing.  We just cant sell it.

**Comment by Skemp45** [comment] 2014-01-13 04:22
I can upload admin tomorrow, spending the rest of the night relaxing. Stayed up till 1 am last night and had to be up at 4am this morning ugh rough day!!!

**Comment by thadius856** [comment] 2014-01-13 04:37
No worries man.

I may not be able to devote any meaningful time until the coming weekend. Lost most of this weekend due to brewing 21 gallons and kegging 21 gallons.

Next weekend is cleared, unless the wife snags my time.

**Comment by Skemp45** [comment] 2014-01-13 05:05
I know things get crazy busy with life, but we should make a target release date so we have a goal to work towards.

**Comment by thadius856** [comment] 2014-01-13 05:07
We need a full features list first.

Will create new issue.

**Comment by Skemp45** [comment] 2014-01-13 17:56
http://raspberrypints.com/site/

I have also been working on this on the side, what do you think?

**Comment by thadius856** [comment] 2014-01-14 04:17
Nice.

The center thing with the three images (montage? no idea what that's called). It's hard to tell they're three images. Maybe a glow or outline around the active image would help? Or even a shadow?

**Comment by thadius856** [comment] 2014-01-18 19:19
Closing. Will continue in new issue.

**Closed as completed by thadius856** 2014-01-18 19:19 UTC
