### ISSUE TITLE
Bug? or fat-finger?

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#121] opened 2014-02-08 07:22 UTC
![image](https://f.cloud.github.com/assets/6321429/2116608/8f973b64-9091-11e3-96fa-778341436494.png)

Anyone else getting this?  My Account page is:

![image](https://f.cloud.github.com/assets/6321429/2116610/9fa0244e-9091-11e3-843c-4e420d03146a.png)

I know I typed in this information when I installed.  I've done it plenty of times.

**Comment by EmDubeu** [comment] 2014-02-08 07:24
Yes,  I got that too.

**Comment by EmDubeu** [comment] 2014-02-08 07:25
Is there an option for us to update this info?

**Comment by thadius856** [comment] 2014-02-08 13:12
Dug through both `left_bar.php` and `Mya.php`. They are working as intended.

The problem is that's the data showing up in the `users` table. It's not getting set properly by the install page.

**Comment by thadius856** [comment] 2014-02-08 13:19
Found it. `install/includes/configprocessor.php` line 192:

```
    $sql = "INSERT INTO users (username, password, name, email, createdDate, modifiedDate) VALUES ('" . $adminuser . "','" . $adminhash . "','name','email','" . $currentdate . "','" . $currentdate . "');";
```

Trying to figure out the fix now.

**Comment by thadius856** [comment] 2014-02-08 13:24
Committed and tested. Closing as fixed.

![untitled](https://f.cloud.github.com/assets/6320180/2117307/465884fc-90c4-11e3-932f-f93f8770b458.png)

**Closed as completed by thadius856** 2014-02-08 13:24 UTC
Labels: question
