### ISSUE TITLE
Right-Side Alignment Reveals Empty Space

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#14] opened 2014-01-08 05:56 UTC
During the CSV->SQL conversion/CSS cleanup, some items lost proper alignment.

In particular, the right-most column no longer borders the right-hand side of the display. This is true at both 1920x1200 and 1920x1080. The header and clock display do span 100% for some reason. See screeshot:

![untitled](https://f.cloud.github.com/assets/6320180/1866179/a5967fc2-7829-11e3-9bb0-2c604b14c58a.png)

**Comment by Skemp45** [comment] 2014-01-09 04:37
BUMP, Anyone have any idea on this ANNOYING issue????? it is driving me NUTS

**Comment by JayUnt** [comment] 2014-01-09 13:52
I can take a look at this.  I have to update to get all of the newest merges first.

**Comment by JayUnt** [comment] 2014-01-09 14:09
The problem is that you have all of the columns to a set width (except the tap number, but its display:block so its going to shrink to its content).  But the percents don't add up to 100%.  If you change beer name column width to 45% it looks better.

**Comment by Skemp45** [comment] 2014-01-09 14:17
you referring to 

.TitleBarBeerName, .BeerNameColumn{
    min-height:46px;
    height:auto !important;
    height:46px;
    width: 40%; <<<change to 45?
}

**Comment by Skemp45** [comment] 2014-01-09 14:21
AHH I see what you are saying!! nice.

**Comment by JayUnt** [comment] 2014-01-09 14:23
exactly :)

**Comment by Skemp45** [comment] 2014-01-09 14:26
DUDE, makes it soooooo much better!!!!

**Comment by Skemp45** [comment] 2014-01-09 14:26
want to close this issue out now then

**Comment by Skemp45** [comment] 2014-01-09 14:40
Issue resolved in style.css line 118-123 https://github.com/thadius856/Digital-Taplist/pull/23

**Closed as completed by Skemp45** 2014-01-09 14:40 UTC
Labels: bug

**Comment by thadius856** [comment] 2014-01-09 15:52
Can you guys post a screenshot when you get a chance? I'm tight on time to re-load the repo to my Pi.
