### ISSUE TITLE
Kegs Aren't Assigned In test_data.sql Properly

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#158] opened 2014-02-19 02:27 UTC
Bad time to notice a bug. I know. Look:

![untitled](https://f.cloud.github.com/assets/6320180/2202835/5903b4e0-990d-11e3-9656-1762c453f00d.png)

**Comment by thadius856** [comment] 2014-02-19 02:27
Looks like we have 10 taps feeding off a single keg... :\

**Comment by Skemp45** [comment] 2014-02-19 04:16
![tapsreset](https://f.cloud.github.com/assets/6318869/2203363/55427f44-991c-11e3-8584-bc096c2acb9a.png)

I kicked all the kegs on the taplist and then re added them and it shows them assigned to different kegs, the kegs I assigned them to. It is also not letting me assign it to the same keg which is good. So if you are getting them all to show on keg 1 this must mean an issue with test data setting them to 1 and not an actual functionality issue

**Comment by Skemp45** [comment] 2014-02-19 04:20
Has to be something with this section.

```
INSERT INTO taps(`beerId`, `kegId`, `tapNumber`, `active`, `ogAct`, `fgAct`, `srmAct`, `ibuAct`, `startAmount`, `currentAmount`, `createdDate`, `modifiedDate`)
SELECT b.id, keg.id as kegId, b.id as tapNumber, 1 as active, b.ogEst as ogAct, b.fgEst as fgAct, b.srmEst as srmAct, b.ibuEst as ibuAct, keg.startAmount as startAmount, keg.startAmount as currentAmount, NOW() as createdDate, NOW() as modifiedDate
FROM `beers` as b, (SELECT k.*, kt.maxAmount as startAmount FROM kegs k LEFT JOIN kegTypes kt ON kt.id = k.kegTypeId ORDER BY Id LIMIT 1) as keg;
```

**Comment by thadius856** [comment] 2014-02-19 04:24
Sorry, figured you guys already knew this. :\

**Comment by Skemp45** [comment] 2014-02-19 13:43
anyone apposed to replacing 

```
INSERT INTO taps(`beerId`, `kegId`, `tapNumber`, `active`, `ogAct`, `fgAct`, `srmAct`, `ibuAct`, `startAmount`, `currentAmount`, `createdDate`, `modifiedDate`)
SELECT b.id, keg.id as kegId, b.id as tapNumber, 1 as active, b.ogEst as ogAct, b.fgEst as fgAct, b.srmEst as srmAct, b.ibuEst as ibuAct, keg.startAmount as startAmount, keg.startAmount as currentAmount, NOW() as createdDate, NOW() as modifiedDate
FROM `beers` as b, (SELECT k.*, kt.maxAmount as startAmount FROM kegs k LEFT JOIN kegTypes kt ON kt.id = k.kegTypeId ORDER BY Id LIMIT 1) as keg;
```

With 

```
INSERT INTO `taps` VALUES(1, 1, 1, 1, 1, 1.066, 1.016, 38.0, 66, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:36');
INSERT INTO `taps` VALUES(2, 2, 2, 2, 1, 1.074, 1.018, 17.8, 27, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:14');
INSERT INTO `taps` VALUES(3, 3, 3, 3, 1, 1.040, 1.009, 2.9, 14, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:20');
INSERT INTO `taps` VALUES(4, 4, 4, 4, 1, 1.066, 1.016, 38.0, 66, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:25');
INSERT INTO `taps` VALUES(5, 5, 5, 5, 1, 1.051, 1.011, 5.0, 39, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:31');
INSERT INTO `taps` VALUES(6, 6, 6, 6, 1, 1.055, 1.014, 5.6, 53, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:43');
INSERT INTO `taps` VALUES(7, 7, 7, 7, 1, 1.035, 1.012, 19.1, 20, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:47');
INSERT INTO `taps` VALUES(8, 8, 8, 8, 1, 1.070, 1.009, 0.0, 0, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:52');
INSERT INTO `taps` VALUES(9, 9, 9, 9, 1, 1.000, 1.000, 0.0, 0, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:32:56');
INSERT INTO `taps` VALUES(10, 10, 10, 10, 1, 1.000, 1.000, 0.0, 0, 5.0, 5.0, '2014-02-18 21:18:33', '2014-02-19 06:33:02');
INSERT INTO `taps` VALUES(16, 2, 4, 11, 0, 1.074, 1.018, 17.8, 27, 5.0, 5.0, '2014-02-19 06:29:50', '2014-02-19 06:29:54');
```

**Comment by Skemp45** [comment] 2014-02-19 13:46
This would need to be updated within the install folder where we import the test data.

**Comment by thadius856** [comment] 2014-02-19 14:52
Seems like a lot of changes for what probably amounts to a single letter mistake, especially with such elegant code.

@JayUnt You wrote this piece. Does it stick out at you why it's not incrementing the keg #?

**Comment by Skemp45** [comment] 2014-02-19 15:02
For sure. if @JayUnt  can fix this Picasso of a script I am all for that. :dancer:

**Comment by JayUnt** [comment] 2014-02-19 20:26
Ill take a look.  the reason it was initially written like that was because i was trying to avoid hard coding beer ids and keg ids in case at some point we didn't start with id 1.

**Comment by JayUnt** [comment] 2014-02-19 22:05
Ok so i figured this little guy out.  I made the query attach a random keg to each tap.  

However i am getting an error with some column differences.  The query is trying to insert the keg.startAmount into the tap.startAmount.  However keg.startAmount does not exist.  We now have a weight.  

Is there a specific formula i should use to convert the weight into an amount?

**Comment by Skemp45** [comment] 2014-02-20 13:47
hummm, im unsure on this. We need to do something ASAP though I would rather not release it with a known bug.

anyone have any input

**Comment by Boombrewer** [comment] 2014-02-20 14:44
Well, volume = mass x SG.  The issue is with the units.  So....

tap.startAmount = (keg.fullWeight - keg.emptyWeight) x finalGravity

I'm not sure if those are the exact variables used in the code.  Also, I can't find the equation using standard units - only metric.  So if you're mass was in grams, your volume would be in milliliters.  Let me keep tinkering and see if I can verify the units.

Also, does this have to be perfect before V1 release?  Its really only there as a demonstration I'm pretty sure since this part of the program is only important if you're running flow sensors and displaying "keg status".

**Comment by Boombrewer** [comment] 2014-02-20 15:06
I really hate that we don't use the metric system like the rest of the world.

**Comment by Boombrewer** [comment] 2014-02-20 15:24
Ran some numbers, this works.  If the kegs are measured in pounds and the desired output is in ounces:

tap.startAmount = (keg.fullWeight - keg.emptyWeight) x finalGravity x 15.338

For our friends in the rest of the world, measure the kegs in g and if you want output in mL and drop the constant off the end.

**Comment by thadius856** [comment] 2014-02-20 16:02
Weight? Uhhh. Isn't that a v2 thing?

**Comment by Skemp45** [comment] 2014-02-20 17:36
alright, we might need to release with the test data pulling from the same Keg

**Comment by JayUnt** [comment] 2014-02-20 18:29
It looks like this is broken in master's sql scripts.  The tap doesn't have a startAmount, but the test data is trying to add it.  Thats just me looking at the queries, but if these have been tested and it works, lets go with what we have.

Truthfully, i just did the test_data.sql for us developers, without thinking it was going to go to the public.  Just a fast way for use to refresh our db and give it data.  To me, a user can start from scratch and put their own data in.  But that is not me saying to rip it out at this point.

**Comment by Skemp45** [comment] 2014-02-20 19:07
maybe in v2 we wont have test data... we will see lets just leave it as is
there is no actual functionality issue

**Comment by Skemp45** [comment] 2014-02-20 19:13
lets go ahead and close this out and focus the rest of the day on polishing cool?

**Closed as completed** 2014-02-20 19:14 UTC
Labels: bug
