### ISSUE TITLE
Modify ABV Graphics

### ISSUE THREAD

**Issue by sevlabs** [RaspberryPints/RaspberryPints#76] opened 2014-01-30 23:47 UTC
I'm thinking about modifying the ABV graphics to show only 1 pint glass. If alcohol-free beverage then the glass will be empty. As the ABV goes up, the pint glass becomes more and more full. Basically the same behavior as now but with a single glass instead of multiple glasses. Any concerns with this?

**Comment by JayUnt** [comment] 2014-01-31 01:27
That would be Thad's call.

**Comment by thadius856** [comment] 2014-01-31 01:40
The ABV graphics do not show pint glasses.

They show shot glasses, which display the equivalent amount of 80-proof liquor to that particular beer.

**Comment by thadius856** [comment] 2014-01-31 01:41
IF you can make it an option in the admin panel to replace the shot glasses with a single pint glass, and it's not enabled by default, go to town.

**Comment by JayUnt** [comment] 2014-01-31 01:44
I think we should pick one and stick with it. Having an option to pick one
or two glasses might be confusing to the user. They wouldn't know why there
are two choices for the same thing.

**Comment by sevlabs** [comment] 2014-01-31 03:32
My bad thinking the ABV glasses were pint glasses. I thought they were beer glasses since they are similar in size to the pint glasses on the far left - and the RP logo. Several other people I showed it to were also puzzled about their meaning.

**Comment by thadius856** [comment] 2014-01-31 03:36
If you have ideas for making it more obvious they're not pints, I'm all ears.

**Comment by Boombrewer** [comment] 2014-01-31 05:29
Yeah, to be honest, I didn't make the shot glass of 80proof equivalent relation until someone said it. 

Personally I think it's likely due to the size relation.

**Comment by EmDubeu** [comment] 2014-01-31 05:31
ditto. keep up the good work, though. :)

On Thu, Jan 30, 2014 at 9:29 PM, Boombrewer notifications@github.comwrote:

> Yeah, to be honest, I didn't make the shot glass of 80proof equivalent
> relation until someone said it.
> 
> Personally I think it's likely due to the size relation.
> 
> Sent from Casey's iPad
> 
> > On Jan 30, 2014, at 19:36, thadius856 notifications@github.com wrote:
> > 
> > If you have ideas for making it more obvious they're not pints, I'm all
> > ears.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/76#issuecomment-33762779
> .

## 

Mike Wright

**Comment by sevlabs** [comment] 2014-01-31 14:10
If it were me I would remove the current shot glass graphics and display ABV and calories text values only... or replace the shot glasses with a simple high/low graphical indicator of some sort and drop the "ABV is equivalent to this many 80-proof shots" display.

A third possibility is to add an option in the control panel (ConfigNames::ShowAbvShotGlasses) to allow the user to choose if they want the shot glasses displayed with ABV. If "ShowAbvShotGlasses" is not checked in the control panel, ABV and calories will display as text values only - centered in that field.

**Comment by sevlabs** [comment] 2014-01-31 19:26
Here's a quick mock up of the display without the shot glasses.
![abv_text](https://f.cloud.github.com/assets/6545107/2053866/855e1e40-8aad-11e3-9ae6-609cf8b71f53.jpg)

**Comment by thadius856** [comment] 2014-01-31 20:52
Run with being able to turn off the graphic via binary type value in table config. Default should be set to display, so column should be hideAbvImage. Add to admin panel as checkbox on Configuration page.

Please branch, commit, push and initiate a pull request for review once complete.

**Comment by JayUnt** [comment] 2014-01-31 21:53
@SevenXXX what browser are you using?  It looks like the SRM masks are not working as intended.  I can see the brown color outside the lines of the glass.

**Comment by sevlabs** [comment] 2014-01-31 22:02
Firefox 26 on Windows PC. I'm not developing on a RaspberryPi if that makes a difference. I'm using WAMP.

**Comment by JayUnt** [comment] 2014-01-31 22:44
Thad, do you care off out breaks in Firefox?  I can look into it, but if
you only want to support chrom let me know.

**Comment by thadius856** [comment] 2014-02-01 00:51
Negative. Dont care if anything other than Chromium looks bad.

Looks into this one previously. F2F refuses to mask images, only solid
colors. This is a known issue with a MDN ticket open.

It'll probably be added in future versions. So it'll probably fix itself of
we wait long enough.

**Comment by thadius856** [comment] 2014-02-02 00:38
Any luck on this one, Seven?

**Comment by sevlabs** [comment] 2014-02-02 03:42
I had to work all day today and tomorrow is the super bowl so I plan to spend it away from the computer. I'll hit this on Monday for sure. May need some help with the config file as I haven't looked into that yet.

**Comment by sevlabs** [comment] 2014-02-02 04:03
Updating the index.php and styles.css files won't take me long. I've already done it locally when creating the mock up. Just need to do it again using the "branch, commit, push, pull" that you mentioned. I'm new to Github.

**Comment by thadius856** [comment] 2014-02-02 07:12
I'll consider making a step-by-step with pictures for TortoiseGit.

**Comment by sevlabs** [comment] 2014-02-03 16:07
Just a general question. If I pull down the latest .zip for RaspberryPints right now should the admin panel work, assuming I have the database up and all other connection files in place? Yesterday when I tried I got the tap list to display but couldn't bring the admin panel up. I did create the user in the DB but still no luck. Wondering if it's something on my side. Thanks.

**Comment by sevlabs** [comment] 2014-02-03 16:56
Actually, the admin panel comes up fine but when I click "show/hide columns" on the left of the main admin screen it gives me a  "Warning: require(includes/configp.php failed to open stream" error. Wondering if this is something in the code or my config that is causing this.

**Comment by Skemp45** [comment] 2014-02-03 17:01
do you have the admin/includes/configp.php file?

**Comment by sevlabs** [comment] 2014-02-03 17:33
I thought I did but checking again this morning it looks like I was in the wrong folder. I'm going to try rebuilding my install/DB with the latest .zip file.

**Comment by sevlabs** [comment] 2014-02-03 18:05
I reinstalled everything using the latest zip file and I get a bit farther now. When I try to save "show/hide ABV Column" setting from the admin page - I get this error. Is there some other configuration setting I need to make to get this setting to stick?
![save_setting](https://f.cloud.github.com/assets/6545107/2067582/983b08e6-8cfd-11e3-91e2-b6c59cf24fe7.png)
![config_error](https://f.cloud.github.com/assets/6545107/2067584/9b578d1a-8cfd-11e3-9202-c5e37dab7938.jpg)

**Comment by sevlabs** [comment] 2014-02-03 19:47
I got the setting to work by changing the showAbvCol in the database to 0.

**Comment by sevlabs** [comment] 2014-02-03 22:55
I'm trying to get the ShowAbvImage option to show up in the admin panel. I added a new row to the DB and also added another constant to config_names.php but it still doesn't show up on the admin panel. Can someone please tell me what I'm missing here?
![config_table](https://f.cloud.github.com/assets/6545107/2071246/35b8f93e-8d26-11e3-9980-b3607bc07bd1.jpg)
![config_names](https://f.cloud.github.com/assets/6545107/2071247/3c7ecdf2-8d26-11e3-9b82-8e828572f3f1.jpg)
![show_hide_columns](https://f.cloud.github.com/assets/6545107/2071249/3f995994-8d26-11e3-9b80-ea9f812bd88c.jpg)

**Comment by sevlabs** [comment] 2014-02-03 23:31
Once this admin panel item is added then this item can be closed. All other changes are completed.

**Comment by thadius856** [comment] 2014-02-04 01:17
Seven, I think your admin panel has a version mismatch against your db schema.

Drop the raspberrypints table entirely. Extract the most recent commit. Point your browser at the install subfolder.

Let me know if it works better.

**Comment by sevlabs** [comment] 2014-02-04 03:18
I rebuilt the database from scratch this afternoon using the latest schema. Do you think it has been updated since then?

**Comment by thadius856** [comment] 2014-02-04 03:38
Probably not. Lemme test mine.

**Comment by thadius856** [comment] 2014-02-04 03:42
ABV column turns off just fine for me.

http://thadius856.servebeer.com

**Comment by sevlabs** [comment] 2014-02-04 03:51
Maybe I have an issue with my DB config. Shall I commit, push, then create a pull request now? I'm hoping the updates I made will work properly on your side.

**Comment by thadius856** [comment] 2014-02-04 03:54
If you created a new branch, that's fine.

**Comment by sevlabs** [comment] 2014-02-04 04:04
I'm getting permission denied when trying to push.
![push](https://f.cloud.github.com/assets/6545107/2073157/6a85b82a-8d51-11e3-95df-a6bc584d23a9.jpg)

**Comment by thadius856** [comment] 2014-02-04 04:26
One sec. Will fix permissions.

**Comment by thadius856** [comment] 2014-02-04 04:27
Try again.

**Comment by sevlabs** [comment] 2014-02-04 04:57
Pull request created. Let me know if any issues with these changes. I wasn't able to get the config values to save to the DB from the admin page with my setup. I may have something wrong with my DB config.

**Comment by thadius856** [comment] 2014-02-04 04:59
Did you provide the install scripts with your root pw for MySQL?

**Comment by sevlabs** [comment] 2014-02-04 05:09
I don't think so. I created the DB from the import tool in myPHPadmin. I then imported the tap list, created a "beer" user in the users table, and copied various config files into place by hand.... nothing with the install scripts. Is there a setup guide that I can try using instead of my hacking?

**Comment by thadius856** [comment] 2014-02-04 05:16
Hehe. Yes. Thought I gave you this earlier...

Create a view-only account in MySQL. I went with l/p beer//beer.

Drop your raspberrypints table. Empty out /var/www. Extract the zip into
/var/www.

Point your web browser at http://your.ip.goes.here/install

The "beer" user is the view-only login/pw.
The "root" user is your admin login/pw.

Load sample data.

Once the script finishes, it should be 100% set up.

**Comment by sevlabs** [comment] 2014-02-04 14:01
OK, I got the DB working and it now saves my admin panel settings correctly in the DB. Please discard pull request #92. I found one item that needs to be changed in index.php. Also, I'm still trying to figure out why it's not showing the new option "ShowAbvImage" on the admin panel. I did add the new constant to config_names.php and a record for this item in the config table. Any ideas what I may be missing to get this option to display on the admin page?

**Comment by thadius856** [comment] 2014-02-04 14:03
Only the first x number of options are displayed. I think its 7.

Dig deeper in the appropriate manager.

**Comment by Skemp45** [comment] 2014-02-04 14:03
^ I will look into adding it to the admin panel

**Comment by Skemp45** [comment] 2014-02-04 14:04
first 6 are
        $stmt = $conn->prepare('SELECT \* FROM config WHERE id <= 6');

**Comment by Skemp45** [comment] 2014-02-04 14:09
ok, so you created  const ShowCalCol = 'showCalCol';
but there is no     showCalCol in the database for it to enable and disable.

**Comment by thadius856** [comment] 2014-02-04 14:10
LOL:)

**Comment by Skemp45** [comment] 2014-02-04 14:19
is this just supposed to remove the calories from the index.php page?

**Comment by sevlabs** [comment] 2014-02-04 14:22
No, it's a new option to toggle displaying the shot glasses in the ABV output. Like you said, it looks like it's only displaying the first 6 items from the config table. However my new item "ShowAbvImage" is #15 in the config table.

**Comment by sevlabs** [comment] 2014-02-04 14:23
So that explains why it's not showing up on the admin page.

**Comment by thadius856** [comment] 2014-02-04 14:24
So add #15 then.

15 sounds high. You sure?

**Comment by sevlabs** [comment] 2014-02-04 14:26
![config](https://f.cloud.github.com/assets/6545107/2076764/4897a050-8da8-11e3-8780-2316daa56259.jpg)

**Comment by Skemp45** [comment] 2014-02-04 14:27
oh is this not committed to the main?

**Comment by sevlabs** [comment] 2014-02-04 14:31
No it's not committed to master yet. Shall I add a new entry to also display item #15 from the config table? Things might get kinda wonky if we do it this way.

**Comment by Skemp45** [comment] 2014-02-04 14:40
or 

```

CREATE TABLE `config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `configName` varchar(50) NOT NULL,
  `configValue` longtext NOT NULL,
  `displayName` varchar(65) NOT NULL,
  `createdDate` timestamp NULL DEFAULT NULL,
  `modifiedDate` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `configName_UNIQUE` (`configName`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=15 ;

--
-- Dumping data for table `config`
--

INSERT INTO `config` VALUES(1, 'showTapNumCol', '1', 'Tap Column', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(2, 'showSrmCol', '1', 'SRM Column', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(3, 'showIbuCol', '1', 'IBU Column', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(4, 'showAbvCol', '1', 'ABV Column', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(5, 'showKegCol', '0', 'Keg Column', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(6, 'useHighResolution', '0', '4k Monitor Support', '2014-02-01 20:17:36', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(7, 'showCalCol', '1', 'Calories Option', '2014-02-04 07:29:37', '2014-02-04 07:12:14');
INSERT INTO `config` VALUES(8, 'showAbvImage', '1', 'Show ABV Image', '2014-02-04 07:40:28', '2014-02-04 07:40:26');
INSERT INTO `config` VALUES(9, 'logoUrl', 'img/logo.png', 'Logo Url', '2014-02-04 07:39:42', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(10, 'headerText', 'Currently On Tap', 'Header Text', '2014-02-04 07:39:35', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(11, 'numberOfTaps', '10', 'Number of Taps', '2014-02-04 07:39:30', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(12, 'versionMajor', '1', 'Major Version', '2014-02-04 07:39:25', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(13, 'versionMinor', '0', 'Minor Version', '2014-02-04 07:39:17', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(14, 'versionRelease', '0', 'Release Number', '2014-02-04 07:39:12', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(15, 'versionBuild', '265', 'Build Number', '2014-02-04 07:39:06', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(16, 'adminLogoUrl', 'admin/img/logo.png', 'Admin Logo Url', '2014-02-04 07:38:58', '2014-02-02 04:08:29');
```

**Comment by Skemp45** [comment] 2014-02-04 14:41
and change in admin/includes/configp.php 

from

```
$stmt = $conn->prepare('SELECT * FROM config WHERE id <= 6');
```

to 

```
$stmt = $conn->prepare('SELECT * FROM config WHERE id <= 8');
```

**Comment by Skemp45** [comment] 2014-02-04 14:43
tested that^^^ and it works

**Comment by mtnbound** [comment] 2014-02-04 14:55
I would say that it's probably best to use the name column instead of selecting by ID. There's no guarantee that the ID will always be the same. In fact, it's probably already different since I remove the 4 version configs, and just made it a single one, which would theoretically, make ID#16, now #13.

We can guarantee that the name will always be the same.

I was going to work on changing the admin and main index page today to lookup by name, not id today.

**Comment by sevlabs** [comment] 2014-02-04 15:03
Agreed selecting a specific row is not a good idea as it will break if things change down the road. I will proceed with Skemp's suggestions to rebuild the config table assuming it won't break anything else.

**Comment by thadius856** [comment] 2014-02-04 15:13
That works, for now. We can't be doing this way once we release.

Better way would be to add to the WHERE statement.

WHERE a is b AND WHERE b is c

These 6 or 7 or 15 options should really be specified individually instead
of in a pool like we have been.

**Comment by sevlabs** [comment] 2014-02-04 15:18
I was thinking the same thing... separate config tables for each area would probably be best.

**Comment by Skemp45** [comment] 2014-02-04 15:23
so explain what you want to do with separate config tables? I agree with not using id's name would be better practice

**Comment by thadius856** [comment] 2014-02-04 15:29
Not separate config files.

Right now, we draw id's 1-7 using a for loop. It would be better practice
to either hard code each one out.

Alternatively, we could add another column like "showOnPanel" as type
tinyint. So the showXxxCol ones get 1, settings for a dofferent page get
to, etc. Instead of calling by WHERE I'd <= x, use WHERE showOnPanel == 1
(or 2 or etc).

**Comment by JayUnt** [comment] 2014-02-04 15:37
I agree with adding a column to the config table a "showOnPanel" or "adminEditable".  Or we just update the query to use:

`"configName IN ( '" . ConfigNames::ShowTapNumCol . "', '" . ConfigNames::ShowSrmCol . "' )"`

**Comment by Skemp45** [comment] 2014-02-04 15:39
Yeah I like it, very smart idea :+1:

**Comment by Skemp45** [comment] 2014-02-04 15:44
```
CREATE TABLE `config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `configName` varchar(50) NOT NULL,
  `configValue` longtext NOT NULL,
  `displayName` varchar(65) NOT NULL,
  `showOnPanel` tinyint(2) NOT NULL,
  `createdDate` timestamp NULL DEFAULT NULL,
  `modifiedDate` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `configName_UNIQUE` (`configName`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

--
-- Dumping data for table `config`
--

INSERT INTO `config` VALUES(1, 'showTapNumCol', '1', 'Tap Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(2, 'showSrmCol', '1', 'SRM Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(3, 'showIbuCol', '1', 'IBU Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(4, 'showAbvCol', '1', 'ABV Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(5, 'showKegCol', '0', 'Keg Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(6, 'useHighResolution', '0', '4k Monitor Support', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(7, 'showCalCol', '1', 'Calories Option', 1, '2014-02-04 08:42:15', '2014-02-04 07:12:14');
INSERT INTO `config` VALUES(8, 'showAbvImage', '1', 'Show ABV Image', 1, '2014-02-04 08:42:15', '2014-02-04 07:40:26');
INSERT INTO `config` VALUES(9, 'logoUrl', 'img/logo.png', 'Logo Url', 0, '2014-02-04 07:39:42', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(10, 'headerText', 'Currently On Tap', 'Header Text', 0, '2014-02-04 07:39:35', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(11, 'numberOfTaps', '10', 'Number of Taps', 0, '2014-02-04 07:39:30', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(12, 'versionMajor', '1', 'Major Version', 0, '2014-02-04 07:39:25', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(13, 'versionMinor', '0', 'Minor Version', 0, '2014-02-04 07:39:17', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(14, 'versionRelease', '0', 'Release Number', 0, '2014-02-04 07:39:12', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(15, 'versionBuild', '265', 'Build Number', 0, '2014-02-04 07:39:06', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(16, 'adminLogoUrl', 'admin/img/logo.png', 'Admin Logo Url', 0, '2014-02-04 07:38:58', '2014-02-02 04:08:29');
```

**Comment by Skemp45** [comment] 2014-02-04 15:44
```
        $stmt = $conn->prepare('SELECT * FROM config WHERE showOnPanel = 1');
        $stmt->execute();
        $result = $stmt->fetchAll();
```

**Comment by Skemp45** [comment] 2014-02-04 15:45
I changed on my site and its working

**Comment by thadius856** [comment] 2014-02-04 15:51
Awesome.

Ill address merging the master and new branch this evening, if nobody beats
me to it first.

Will probably also make a few more static branches for proper dev cycles
and update the HOW TO issue.

**Comment by sevlabs** [comment] 2014-02-04 15:57
Should I hold off making changes until we get a new master? Was hoping to have this done yesterday but now it seems there is more work needed here. Just confirming what my next steps should be. Thanks.

**Comment by sevlabs** [comment] 2014-02-04 18:46
I just noticed Skemp gave the SQL to rebuild the table and I'll do it now. Any issues with re-arranging the config table as follows? I moved the "showAbvImage" up a few so it would be displayed immediately following "showAbvCol"

**Comment by sevlabs** [comment] 2014-02-04 18:46
CREATE TABLE `config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `configName` varchar(50) NOT NULL,
  `configValue` longtext NOT NULL,
  `displayName` varchar(65) NOT NULL,
  `showOnPanel` tinyint(2) NOT NULL,
  `createdDate` timestamp NULL DEFAULT NULL,
  `modifiedDate` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `configName_UNIQUE` (`configName`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

## 

## -- Dumping data for table `config`

INSERT INTO `config` VALUES(1, 'showTapNumCol', '1', 'Tap Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(2, 'showSrmCol', '1', 'SRM Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(3, 'showIbuCol', '1', 'IBU Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(4, 'showAbvCol', '1', 'ABV Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(5, 'showAbvImage', '1', 'Show ABV Image', 1, '2014-02-04 08:42:15', '2014-02-04 07:40:26');
INSERT INTO `config` VALUES(6, 'showKegCol', '0', 'Keg Column', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(7, 'useHighResolution', '0', '4k Monitor Support', 1, '2014-02-04 08:42:15', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(8, 'showCalCol', '1', 'Calories Option', 1, '2014-02-04 08:42:15', '2014-02-04 07:12:14');
INSERT INTO `config` VALUES(9, 'logoUrl', 'img/logo.png', 'Logo Url', 0, '2014-02-04 07:39:42', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(10, 'headerText', 'Currently On Tap', 'Header Text', 0, '2014-02-04 07:39:35', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(11, 'numberOfTaps', '10', 'Number of Taps', 0, '2014-02-04 07:39:30', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(12, 'versionMajor', '1', 'Major Version', 0, '2014-02-04 07:39:25', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(13, 'versionMinor', '0', 'Minor Version', 0, '2014-02-04 07:39:17', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(14, 'versionRelease', '0', 'Release Number', 0, '2014-02-04 07:39:12', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(15, 'versionBuild', '265', 'Build Number', 0, '2014-02-04 07:39:06', '2014-02-01 20:17:36');
INSERT INTO `config` VALUES(16, 'adminLogoUrl', 'admin/img/logo.png', 'Admin Logo Url', 0, '2014-02-04 07:38:58', '2014-02-02 04:08:29');

**Comment by mtnbound** [comment] 2014-02-04 19:07
Just remove the 4 version rows, and replace with one row named "config" and a value of 1.0.0.265

**Comment by sevlabs** [comment] 2014-02-04 19:25
All changes completed and working correctly. Pull request #94 submitted.

**Comment by sevlabs** [comment] 2014-02-04 19:26
Sorry mtnbound, I created pull request before seeing your note.

**Comment by mtnbound** [comment] 2014-02-04 19:33
No worries. It's easy to change if it gets merged into master. I changed it in my branch also.

The only thing it breaks is the install pages.

**Comment by thadius856** [comment] 2014-02-05 01:42
Added some repo collab to the Pull Request.

Will merge once addressed.

**Comment by sevlabs** [comment] 2014-02-05 14:20
I installed fresh from the latest master this morning. The install went fine (no errors) and I can see the new ABV image toggle is working correctly. 

What else can I do to help with the project now?

**Comment by thadius856** [comment] 2014-02-05 14:45
Well... let's see.

You could rinse and repeat for the other columns images.

You could rinse and repeat for each text block (IBU, SRM, BU:GU, etc).

Currently, the two text elements and image in each column ride in a single TD. You could fix that and v-align them all center. Edit: I meant "align them all middle".

You could make an option to replace the kCal text block with the number of shots it's equivalent to. ;) "1.68 shots"

**Comment by sevlabs** [comment] 2014-02-05 14:48
No prob...  I'll take a look.

**Comment by thadius856** [comment] 2014-02-05 14:49
Great. If you decide to run with one of these, close this issue and make a new one. If you decide you want to try something else, run it by us (we may have something else planned).

Just play with the thing for a while, and ask yourself "what would I improve?"

**Comment by thadius856** [comment] 2014-02-05 15:06
Theres also some official website work and admin pages to be created, of
youre interested.

See the open issues.

**Comment by thadius856** [comment] 2014-02-06 05:50
Closing as completed.

**Closed as completed by thadius856** 2014-02-06 05:50 UTC
Labels: enhancement

**Comment by sevlabs** [comment] 2014-02-06 14:20
Since issue #76 is closed should I continue working future changes in 
the Modify ABV Graphics branch or should I create a new branch? (I'm 
still learning GitHub best practices).

**Comment by sevlabs** [comment] 2014-02-06 14:29
I'd prefer to create a new branch if possible because I think I mucked up my local copy playing around with TortoiseGit last night.

**Comment by thadius856** [comment] 2014-02-06 14:31
Same branch is perfectly fine.

If you want a new name, we can delete that branch and make a new one. But
no functional difference doing so.

**Comment by sevlabs** [comment] 2014-02-06 14:46
I will create a new branch then...  calling it "Modify Display Options" for adding toggles to the various images shown on the main taplist page. Let me know if this works.

**Comment by thadius856** [comment] 2014-02-06 15:09
I wont be able to see branches until 5pm. Mobile at the gym again.

I generally recommend no dashes in branch names, but if you already created
it, no biggie.
